CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(255) NOT NULL,
    password     VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);