CREATE TABLE words
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                     BIGINT                   NOT NULL,
    term                        VARCHAR(100)             NOT NULL,
    definition                  VARCHAR(150)             NOT NULL,
    level                       INT                      NOT NULL,
    example_sentence            VARCHAR(1000),
    meaning_of_example_sentence VARCHAR(1000),
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_words_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_words_user_id ON words (user_id);