CREATE TABLE quiz_set_attempts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT                   NOT NULL,
    attempt_id    UUID                     NOT NULL,
    set_number    INT                      NOT NULL,
    word_count    INT                      NOT NULL,
    learned_count INT                      NOT NULL,
    completed_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_quiz_set_attempts_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_quiz_set_attempts_user_attempt
        UNIQUE (user_id, attempt_id),
    CONSTRAINT ck_quiz_set_attempts_set_number
        CHECK (set_number >= 1),
    CONSTRAINT ck_quiz_set_attempts_word_count
        CHECK (word_count BETWEEN 1 AND 30),
    CONSTRAINT ck_quiz_set_attempts_learned_count
        CHECK (learned_count BETWEEN 0 AND word_count)
);

CREATE INDEX idx_quiz_set_attempts_user_set
    ON quiz_set_attempts (user_id, set_number, completed_at);
