ALTER TABLE users
    ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE users
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE users
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE users
    ADD COLUMN last_login_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE users
    ADD COLUMN last_active_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE users
    ADD COLUMN withdrawn_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE users
    ADD CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'));

ALTER TABLE users
    ADD CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'WITHDRAWN'));

CREATE TABLE user_activity_events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    event_type  VARCHAR(40)              NOT NULL,
    path        VARCHAR(255),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_activity_events_type CHECK (
        event_type IN (
            'LOGIN',
            'PAGE_VIEW',
            'WORD_CREATED',
            'AI_GENERATION_REQUESTED',
            'QUIZ_SET_COMPLETED'
        )
    ),
    CONSTRAINT fk_activity_events_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_activity_events_occurred_at
    ON user_activity_events (occurred_at);

CREATE INDEX idx_activity_events_user_occurred_at
    ON user_activity_events (user_id, occurred_at);

CREATE INDEX idx_activity_events_type_occurred_at
    ON user_activity_events (event_type, occurred_at);

CREATE TABLE account_lifecycle_events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT,
    username_snapshot VARCHAR(255)             NOT NULL,
    event_type        VARCHAR(30)              NOT NULL,
    occurred_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_account_lifecycle_events_type CHECK (
        event_type IN ('SIGNUP', 'WITHDRAWAL')
    ),
    CONSTRAINT fk_account_lifecycle_events_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_account_lifecycle_events_occurred_at
    ON account_lifecycle_events (occurred_at);

CREATE INDEX idx_account_lifecycle_events_type_occurred_at
    ON account_lifecycle_events (event_type, occurred_at);
